kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-backend
  template:
    metadata:
      labels:
        app: spring-boot-backend
    spec:
      containers:
        - name: my-java-springboot
          image: rushiops/spring-boot-vue3-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: DB_NAME
            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: APP_PORT
