kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc-1
spec:
  ports:
    - name: http-8088
      port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: sadir-leads-microservice-draft
