apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: expose-service
spec:
  params:
    - name: serviceName
      type: string
      description: Name of the service to expose
    - name: namespace
      type: string
      description: Namespace where the service is located
  steps:
    - name: expose-svc
      image: 'openshift/cli'
      script: |
        SERVICE_NAME=$(params.serviceName)
        NAMESPACE=$(params.namespace)
        oc expose svc $SERVICE_NAME -n $NAMESPACE
        ROUTE=$(oc get route $SERVICE_NAME -n $NAMESPACE -o jsonpath='{.spec.host}')
        echo "Service $SERVICE_NAME is exposed at http://$ROUTE"
