apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: expose-service-pipelinerun
spec:
  pipelineRef:
    name: expose-service-pipeline  # This refers to the pipeline defined earlier
  params:
    - name: serviceName
      value: my-java-springboot-backend-svc # Replace with your service name
    - name: namespace
      value: rushiighutke16-dev     # Replace with your namespace
