apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: expose-service-pipelinerun
spec:
  pipelineRef:
    name: expose-service-pipeline  # This refers to the pipeline defined earlier
  params:
    - name: serviceName
      value: <your-service-name>  # Replace with your service name
    - name: namespace
      value: <your-namespace>     # Replace with your namespace
