kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-frontend
  template:
    metadata:
      labels:
        app: spring-boot-frontend
    spec:
      containers:
        - name: my-java-springboot
          image: rushiops/spring-boot-vue3-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
