kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc-1
spec:
  ports:
    - name: http-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sadir-leads-microservice-draft
